# Generated by Django 2.2.12 on 2020-07-26 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=32)),
                ('createdOn', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 26, 18, 4, 7, 395502))),
                ('lastUpdatedOn', models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 26, 18, 4, 7, 395502))),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
