# Generated by Django 2.2.12 on 2020-10-11 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='createdOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 11, 16, 57, 23, 802611)),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='lastUpdatedOn',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 11, 16, 57, 23, 802611)),
        ),
    ]
